//modals
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

//STUDENTs
export const FETCH_STUDENTS_REQUESTED = "FETCH_STUDENTS_REQUESTED";
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_FAILED = "FETCH_STUDENTS_FAILED";

export const CHANGE_STUDENT = "CHANGE_STUDENT";

export const FETCH_STUDENT_REQUESTED = "FETCH_STUDENT_REQUESTED";
export const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS";
export const FETCH_STUDENT_FAILED = "FETCH_STUDENT_FAILED";

export const NEW_STUDENT = "NEW_STUDENT";
export const SAVE_STUDENT_REQUESTED = "SAVE_STUDENT_REQUESTED";
export const SAVE_STUDENT_SUCCESS = "SAVE_STUDENT_SUCCESS";
export const SAVE_STUDENT_FAILED = "SAVE_STUDENT_FAILED";

export const UPDATE_STUDENT_REQUESTED = "UPDATE_STUDENT_REQUESTED";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAILED = "UPDATE_STUDENT_FAILED";

export const DELETE_STUDENT_REQUESTED = "DELETE_STUDENT_REQUESTED";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAILED = "DELETE_STUDENT_FAILED";

//TEACHERs
export const FETCH_TEACHERS_REQUESTED = "FETCH_TEACHERS_REQUESTED";
export const FETCH_TEACHERS_SUCCESS = "FETCH_TEACHERS_SUCCESS";
export const FETCH_TEACHERS_FAILED = "FETCH_TEACHERS_FAILED";

export const CHANGE_TEACHER = "CHANGE_TEACHER";

export const FETCH_TEACHER_REQUESTED = "FETCH_TEACHER_REQUESTED";
export const FETCH_TEACHER_SUCCESS = "FETCH_TEACHER_SUCCESS";
export const FETCH_TEACHER_FAILED = "FETCH_TEACHER_FAILED";

export const NEW_TEACHER = "NEW_TEACHER";
export const SAVE_TEACHER_REQUESTED = "SAVE_TEACHER_REQUESTED";
export const SAVE_TEACHER_SUCCESS = "SAVE_TEACHER_SUCCESS";
export const SAVE_TEACHER_FAILED = "SAVE_TEACHER_FAILED";

export const UPDATE_TEACHER_REQUESTED = "UPDATE_TEACHER_REQUESTED";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_FAILED = "UPDATE_TEACHER_FAILED";

export const DELETE_TEACHER_REQUESTED = "DELETE_TEACHER_REQUESTED";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FAILED = "DELETE_TEACHER_FAILED";


//COURSEs
export const FETCH_COURSES_REQUESTED = "FETCH_COURSES_REQUESTED";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILED = "FETCH_COURSES_FAILED";

export const CHANGE_COURSE = "CHANGE_COURSE";

export const FETCH_COURSE_REQUESTED = "FETCH_COURSE_REQUESTED";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_FAILED = "FETCH_COURSE_FAILED";

export const NEW_COURSE = "NEW_COURSE";
export const SAVE_COURSE_REQUESTED = "SAVE_COURSE_REQUESTED";
export const SAVE_COURSE_SUCCESS = "SAVE_COURSE_SUCCESS";
export const SAVE_COURSE_FAILED = "SAVE_COURSE_FAILED";

export const UPDATE_COURSE_REQUESTED = "UPDATE_COURSE_REQUESTED";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAILED = "UPDATE_COURSE_FAILED";

export const DELETE_COURSE_REQUESTED = "DELETE_COURSE_REQUESTED";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILED = "DELETE_COURSE_FAILED";