//modals
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

//STUDENTs
export const FETCH_STUDENTS_REQUESTED = "FETCH_STUDENTS_REQUESTED";
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_FAILED = "FETCH_STUDENTS_FAILED";

export const CHANGE_STUDENT = "CHANGE_STUDENT";

export const FETCH_STUDENT_REQUESTED = "FETCH_STUDENT_REQUESTED";
export const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS";
export const FETCH_STUDENT_FAILED = "FETCH_STUDENT_FAILED";

export const NEW_STUDENT = "NEW_STUDENT";
export const SAVE_STUDENT_REQUESTED = "SAVE_STUDENT_REQUESTED";
export const SAVE_STUDENT_SUCCESS = "SAVE_STUDENT_SUCCESS";
export const SAVE_STUDENT_FAILED = "SAVE_STUDENT_FAILED";

export const UPDATE_STUDENT_REQUESTED = "UPDATE_STUDENT_REQUESTED";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAILED = "UPDATE_STUDENT_FAILED";

export const DELETE_STUDENT_REQUESTED = "DELETE_STUDENT_REQUESTED";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAILED = "DELETE_STUDENT_FAILED";